### ISSUE TITLE
Remove context menu

### ISSUE THREAD

**Issue by gavaletz** [yoichiro/url_shortener_extension#7]
I was just leaving an issue on watching, and I thought I would add this suggestion as well.  What I really wanted was the option to right click on a link in a page and to get that link address as a shortened URL.  I tried repeatedly in a couple different versions of Chrome (I use a dev release), and even re-installed the extension a number of times trying to get it to work.  Finally I realized that I couldn't right click on a link, but just on the page.  In my opinion there is little value in this since you can only get the URL of the tab which is the default action of the extension.  If you cannot shorten the URL of a link wouldn't it be better to simplify the user's experience and get rid of the context menu?

**Comment by yoichiro** [comment]
I could not understand your suggestion. In fact, as the current implementation, users can shorten an URL of a current page by right-clicking the context menu item on the client area of the page, but users can not shorten an URL on the hyper link in the page because the context menu is not displayed at right-clicking on the link. Of course, it is simple and enable to allow users to be clicked on the link, but there is a problem. It is that I cannot decide whether a shortened URL is the current page's URL or the link's URL. Therefore, I implemented not to display the context menu on the link.

I think that the context menu is convenience. Users can shorten the page's URL quickly. If  I have two options, I want to choice one of which the context menu will be displayed and the target shortened URL will be the page's URL.

How does that sound?

**Comment by gavaletz** [comment]
My thoughts are that right clicking on a link should have the option to shorten that URL, I am not sure that having the ability to right click on the page its self offers that much of an advantage over clicking on the extension icon.  That said, I am an engineer and I do not consider my preferences to be similar to the average user.  

The reason I wanted the ability to right click a link is that I like to use short URLs in my reports, and if I have a page with a list of commits and I want to generate short links to a bunch of those commits, then I end up having to open each of the pages before I can shorten them (to paste into my report).

**Comment by yoichiro** [comment]
OK, I think I want to apply your suggestion, but I would like to confirm whether the following changes can fill your idea or not:
- Support the right clicking on a link to shorten URL.
- The user can choose either the page's URL or the link's href URL as the shortened target URL on the option page of this extension.

Does that sound good?

**Comment by yoichiro** [comment]
Today the new version 1.31.0 has been released. It has the new setting and feature described above.

https://github.com/yoichiro/url_shortener_extension/commit/2ef40724ab5fe344258ce412fe2e228747d73178
